name: InspiredNations
main: com.github.InspiredOne.InspiredNationsClient.InspiredNationsClient
version: 1.0
commands:
  hud:
    description: The HUD
  map:
    description: The Map
  npc:
    description: Makes the NPCs buy